package com.infobeans.consumerfinance.dto.response;

import com.infobeans.consumerfinance.domain.enums.LoanApplicationStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Response DTO for Loan Application.
 *
 * Provides a complete snapshot of a loan application including:
 * - Application ID (UUID string, 36 chars)
 * - Consumer ID (UUID string, 36 chars)
 * - Current status (PENDING, APPROVED, REJECTED, CANCELLED)
 * - Financial details (requested amount, term in months)
 * - Loan purpose
 * - Audit timestamps (created_at, updated_at)
 *
 * Used in API responses for loan application submissions and retrievals.
 * Timestamps are formatted as ISO 8601 for JSON compatibility.
 *
 * @author Consumer Finance Service
 * @version 1.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class LoanApplicationResponse {

    /**
     * Unique identifier for the loan application.
     * UUID string (36 characters).
     * Generated by the system upon creation.
     */
    private String id;

    /**
     * Consumer ID who submitted the loan application.
     * UUID string (36 characters).
     * Links the application to the consumer account.
     */
    private String consumerId;

    /**
     * Current status of the loan application.
     * Possible values: PENDING, APPROVED, REJECTED, CANCELLED
     */
    private LoanApplicationStatus status;

    /**
     * The loan amount requested by the consumer.
     * Stored with up to 15 digits and 2 decimal places.
     */
    private BigDecimal requestedAmount;

    /**
     * The desired loan term in months.
     * Optional: may be null if not specified during submission.
     */
    private Integer termInMonths;

    /**
     * The stated purpose of the loan.
     * Optional: may be null if not provided during submission.
     * Max 255 characters.
     */
    private String purpose;

    /**
     * Application submission timestamp.
     * ISO 8601 format: yyyy-MM-dd'T'HH:mm:ss
     * Automatically set by the system.
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime createdAt;

    /**
     * Last update timestamp.
     * ISO 8601 format: yyyy-MM-dd'T'HH:mm:ss
     * Updated whenever the application status or details change.
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime updatedAt;
}
