package com.infobeans.consumerfinance.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.infobeans.consumerfinance.domain.enums.AccountStatus;
import com.infobeans.consumerfinance.dto.request.CreatePrincipalAccountRequest;
import com.infobeans.consumerfinance.dto.response.PrincipalAccountResponse;
import com.infobeans.consumerfinance.exception.DuplicateResourceException;
import com.infobeans.consumerfinance.exception.ResourceNotFoundException;
import com.infobeans.consumerfinance.service.PrincipalAccountService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.hamcrest.Matchers.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Integration tests for PrincipalAccountController.
 * Tests REST endpoints for principal account creation and retrieval with authentication and error handling.
 */
@SpringBootTest
@AutoConfigureMockMvc
@DisplayName("PrincipalAccountController Integration Tests")
class PrincipalAccountControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private PrincipalAccountService principalAccountService;

    private CreatePrincipalAccountRequest validRequest;
    private PrincipalAccountResponse validResponse;
    private String testConsumerId;
    private String validJwt;

    @BeforeEach
    void setUp() {
        testConsumerId = "550e8400-e29b-41d4-a716-446655440000";

        validRequest = CreatePrincipalAccountRequest.builder()
            .consumerId(testConsumerId)
            .accountType("PRIMARY")
            .build();

        validResponse = PrincipalAccountResponse.builder()
            .id("account-id-123")
            .consumerId(testConsumerId)
            .accountType("PRIMARY")
            .status(AccountStatus.ACTIVE)
            .createdAt(LocalDateTime.now())
            .updatedAt(LocalDateTime.now())
            .build();

        // Mock JWT token (in real scenario, this would be generated by login endpoint)
        validJwt = "valid.jwt.token";
    }

    @Test
    @WithMockUser
    @DisplayName("POST /api/v1/principal-accounts - Create principal account successfully")
    void testCreatePrincipalAccount_Success() throws Exception {
        // Arrange
        when(principalAccountService.createPrincipalAccount(any(CreatePrincipalAccountRequest.class)))
            .thenReturn(validResponse);

        // Act & Assert
        mockMvc.perform(post("/api/v1/principal-accounts")
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(validRequest)))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.success", is(true)))
            .andExpect(jsonPath("$.message", containsString("created successfully")))
            .andExpect(jsonPath("$.data.id", is(validResponse.getId())))
            .andExpect(jsonPath("$.data.consumerId", is(testConsumerId)))
            .andExpect(jsonPath("$.data.accountType", is("PRIMARY")));

        verify(principalAccountService).createPrincipalAccount(any());
    }

    @Test
    @WithMockUser
    @DisplayName("POST /api/v1/principal-accounts - Return 404 when consumer does not exist")
    void testCreatePrincipalAccount_ConsumerNotFound() throws Exception {
        // Arrange
        when(principalAccountService.createPrincipalAccount(any()))
            .thenThrow(new ResourceNotFoundException("Consumer", "id", testConsumerId));

        // Act & Assert
        mockMvc.perform(post("/api/v1/principal-accounts")
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(validRequest)))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.error", is("Resource Not Found")))
            .andExpect(jsonPath("$.message", containsString("Consumer")));
    }

    @Test
    @WithMockUser
    @DisplayName("POST /api/v1/principal-accounts - Return 409 when principal account already exists")
    void testCreatePrincipalAccount_DuplicatePrincipalAccount() throws Exception {
        // Arrange
        when(principalAccountService.createPrincipalAccount(any()))
            .thenThrow(new DuplicateResourceException(
                "A principal account already exists for consumer with ID '" + testConsumerId + "'"));

        // Act & Assert
        mockMvc.perform(post("/api/v1/principal-accounts")
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(validRequest)))
            .andExpect(status().isConflict())
            .andExpect(jsonPath("$.error", is("Duplicate Resource")))
            .andExpect(jsonPath("$.message", containsString("already exists")));
    }

    @Test
    @WithMockUser
    @DisplayName("POST /api/v1/principal-accounts - Return 400 for validation errors")
    void testCreatePrincipalAccount_ValidationError_MissingConsumerId() throws Exception {
        // Arrange - request without consumerId
        CreatePrincipalAccountRequest invalidRequest = CreatePrincipalAccountRequest.builder()
            .consumerId(null)
            .accountType("PRIMARY")
            .build();

        // Act & Assert
        mockMvc.perform(post("/api/v1/principal-accounts")
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(invalidRequest)))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.error", is("Validation Error")));
    }

    @Test
    @DisplayName("POST /api/v1/principal-accounts - Return 400 for invalid UUID format")
    @WithMockUser
    void testCreatePrincipalAccount_ValidationError_InvalidUUID() throws Exception {
        // Arrange - request with invalid UUID
        CreatePrincipalAccountRequest invalidRequest = CreatePrincipalAccountRequest.builder()
            .consumerId("invalid-uuid-format")
            .accountType("PRIMARY")
            .build();

        // Act & Assert
        mockMvc.perform(post("/api/v1/principal-accounts")
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(invalidRequest)))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.error", is("Validation Error")));
    }

    @Test
    @DisplayName("GET /api/v1/consumers/{consumerId}/principal-account - Retrieve principal account successfully")
    @WithMockUser
    void testGetPrincipalAccount_Success() throws Exception {
        // Arrange
        when(principalAccountService.getPrincipalAccountByConsumerId(testConsumerId))
            .thenReturn(validResponse);

        // Act & Assert
        mockMvc.perform(get("/api/v1/consumers/{consumerId}/principal-account", testConsumerId)
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.success", is(true)))
            .andExpect(jsonPath("$.message", containsString("retrieved successfully")))
            .andExpect(jsonPath("$.data.id", is(validResponse.getId())))
            .andExpect(jsonPath("$.data.consumerId", is(testConsumerId)));

        verify(principalAccountService).getPrincipalAccountByConsumerId(testConsumerId);
    }

    @Test
    @DisplayName("GET /api/v1/consumers/{consumerId}/principal-account - Return 404 when consumer not found")
    @WithMockUser
    void testGetPrincipalAccount_ConsumerNotFound() throws Exception {
        // Arrange
        when(principalAccountService.getPrincipalAccountByConsumerId(testConsumerId))
            .thenThrow(new ResourceNotFoundException("Consumer", "id", testConsumerId));

        // Act & Assert
        mockMvc.perform(get("/api/v1/consumers/{consumerId}/principal-account", testConsumerId)
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.error", is("Resource Not Found")));
    }

    @Test
    @DisplayName("GET /api/v1/consumers/{consumerId}/principal-account - Return 404 when principal account not found")
    @WithMockUser
    void testGetPrincipalAccount_PrincipalAccountNotFound() throws Exception {
        // Arrange
        when(principalAccountService.getPrincipalAccountByConsumerId(testConsumerId))
            .thenThrow(new ResourceNotFoundException("PrincipalAccount", "consumerId", testConsumerId));

        // Act & Assert
        mockMvc.perform(get("/api/v1/consumers/{consumerId}/principal-account", testConsumerId)
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.error", is("Resource Not Found")))
            .andExpect(jsonPath("$.message", containsString("PrincipalAccount")));
    }

    @Test
    @DisplayName("POST /api/v1/principal-accounts - Return 403 Forbidden without Authorization header")
    void testCreatePrincipalAccount_NoAuthorization() throws Exception {
        // Act & Assert - No Authorization header (Spring returns 403 Forbidden for missing auth)
        mockMvc.perform(post("/api/v1/principal-accounts")
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(validRequest)))
            .andExpect(status().isForbidden());
    }

    @Test
    @DisplayName("GET /api/v1/consumers/{consumerId}/principal-account - Return 403 Forbidden without Authorization header")
    void testGetPrincipalAccount_NoAuthorization() throws Exception {
        // Act & Assert - No Authorization header (Spring returns 403 Forbidden for missing auth)
        mockMvc.perform(get("/api/v1/consumers/{consumerId}/principal-account", testConsumerId)
            .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isForbidden());
    }

    @Test
    @DisplayName("POST /api/v1/principal-accounts - Verify request body is properly mapped")
    @WithMockUser
    void testCreatePrincipalAccount_RequestMapping() throws Exception {
        // Arrange
        when(principalAccountService.createPrincipalAccount(any(CreatePrincipalAccountRequest.class)))
            .thenAnswer(invocation -> {
                CreatePrincipalAccountRequest request = invocation.getArgument(0);
                assertEquals(testConsumerId, request.getConsumerId());
                assertEquals("PRIMARY", request.getAccountType());
                return validResponse;
            });

        // Act & Assert
        mockMvc.perform(post("/api/v1/principal-accounts")
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(validRequest)))
            .andExpect(status().isCreated());

        verify(principalAccountService).createPrincipalAccount(any());
    }

    @Test
    @DisplayName("POST /api/v1/principal-accounts - Response includes all required fields")
    @WithMockUser
    void testCreatePrincipalAccount_ResponseFields() throws Exception {
        // Arrange
        when(principalAccountService.createPrincipalAccount(any()))
            .thenReturn(validResponse);

        // Act & Assert - verify all fields are present in response
        MvcResult result = mockMvc.perform(post("/api/v1/principal-accounts")
            .header("Authorization", "Bearer " + validJwt)
            .contentType(MediaType.APPLICATION_JSON)
            .content(objectMapper.writeValueAsString(validRequest)))
            .andExpect(status().isCreated())
            .andReturn();

        String content = result.getResponse().getContentAsString();
        assertTrue(content.contains("\"id\""), "Response should contain id field");
        assertTrue(content.contains("\"consumerId\""), "Response should contain consumerId field");
        assertTrue(content.contains("\"accountType\""), "Response should contain accountType field");
        assertTrue(content.contains("\"status\""), "Response should contain status field");
        assertTrue(content.contains("\"createdAt\""), "Response should contain createdAt field");
        assertTrue(content.contains("\"updatedAt\""), "Response should contain updatedAt field");
    }
}
